### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by sohailp** [jordan-wright/rapportive#7] opened 2014-01-10 15:15 UTC
I had some troubles in implementing the rapportive script and I believe that I might have missed some or the other thing. Here is the snap of my terminal, please check on it and revert back.

![image](https://f.cloud.github.com/assets/6369953/1888181/004527ca-7a0a-11e3-8822-cdadaba58874.png)

**Comment by jordan-wright** [comment] 2014-01-10 15:36
It looks like there is an error in the JSON response you are getting. Could you try adding the following on line 83 and providing the output:

```
print requests.get(status_url).text
```

**Comment by sohailp** [comment] 2014-01-10 15:42
After adding the given line this is the output which I get.

![image](https://f.cloud.github.com/assets/6369953/1888461/f70a2ac6-7a0d-11e3-8112-1c565ad29a5c.png)

**Comment by jordan-wright** [comment] 2014-01-10 15:59
The output looks the same. Just to check, did you out the print line above the response= line? You need to make sure it prints the response before throwing an error.

If you did do that, then it looks like you are getting an empty response, which could be for a variety of reasons.

**Comment by sohailp** [comment] 2014-01-10 16:25
After adding the given line this is the output which I get.

![image](https://f.cloud.github.com/assets/6369953/1888902/c5e06842-7a13-11e3-9c9a-cbe347c6a801.png)

This script is being run from an ec2 micro instance so is this the reason for this error?

**Comment by jordan-wright** [comment] 2014-01-10 16:32
This may very well be the reason. It does appear to be geographic, and I can confirm that I am still able to receive results using the script.

You may try a different instance in a different region to see if that resolves the problem.

Since this is not an issue with the script, I will close this issue. Let me know if you run into any further issues.

**Closed as completed by jordan-wright** 2014-01-10 16:32 UTC

**Comment by sohailp** [comment] 2014-01-10 16:36
Ok I will try it out on Hard installed system. Hope it works out there. Thanks for supporting and reverting back.
